// frontend/src/jobPosts.js
export const jobPosts = [
    { id: 1,company: 'Google', title: 'Full Stack Developer', description: 'Work on web applications.', requirements: 'Must have experience in web development, including HTML, CSS, JavaScript, and PHP.', salary: '90k-120k', applyLink: '#',lastUpdated: 'Last updated 1 day ago' },
    { id: 2,company: 'Amazon', title: 'Data Scientist', description: 'Analyze data.', requirements: 'Must have experience in data analysis, machine learning, and statistical modeling.', salary: '120k-160k', applyLink: '#', lastUpdated: 'Last updated 1 day ago' },
    { id: 3,company: 'Facebook', title: 'UI/UX Designer', description: 'Design user interfaces.', requirements: 'Must have experience in user interface design, including wireframes, prototypes, and visual design.', salary: '70k-90k', applyLink: '#',lastUpdated: 'Last updated 2 day ago'  },
    { id: 4,company: 'Microsoft', title: 'Project Manager', description: 'Manage projects.', requirements: 'Must have experience in project management, including time management, budgeting, and resource allocation.', salary: '100k-150k', applyLink: '#',lastUpdated: 'Last updated 4 hours ago' },
    {id: 5, company: 'Netflix', title: 'Backend Developer', description: 'Work on server-side applications.', requirements: 'Must have experience in backend development, including Node.js, Python, and Ruby on Rails.', salary: '80k-100k', applyLink: '#', lastUpdated: 'Last updated 3 days ago'},
    {id: 6, company: 'Google', title: 'QA Engineer', description: 'Test software.', requirements: 'Must have experience in software testing, including unit testing, integration testing, and user acceptance testing.', salary: '80k-100k', applyLink: '#', lastUpdated: 'Last updated 6 hours ago'},
    {id: 7, company: 'Amazon', title: 'Android Developer', description: 'Work on mobile applications.', requirements: 'Must have experience in Android development, including Java, Kotlin, and XML.', salary: '140k-190k', applyLink: '#',lastUpdated: 'Last updated 1 month ago' },
    {id: 8, company: 'Apple', title: 'iOS Developer', description: 'Work on mobile applications.', requirements: 'Must have experience in iOS development, including Swift, Objective-C, and Xcode.', salary: '130k-180k', applyLink: '#',lastUpdated: 'Last updated 6 days ago'},
    {id: 9, company: 'Microsoft', title: 'Web Developer', description: 'Work on web applications.', requirements: 'Must have experience in web development, including HTML, CSS, JavaScript, and PHP.', salary: '100k-150k', applyLink: '#',lastUpdated: 'Last updated 1 hours ago'},
    {id: 10, company: 'Facebook', title: 'Database Administrator', description: 'Administer databases.', requirements: 'Must have experience in database administration, including MySQL, PostgreSQL, and MongoDB.', salary: '110k-150k', applyLink: '#',lastUpdated: 'Last updated 20 days ago'},
  ];